### ISSUE TITLE
Procedure 'box.execute' is not defined (0x21)

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool-operator#56]
What's the possible cause of error if when doing locally using docker it works fine, but when using this tarantool operator on a kubernetes deployment, it shows an error when called from `go-tarantool` client?

**Comment by Totktonada** [comment]
0x21 or 33 is the [ER_NO_SUCH_PROC](https://github.com/tarantool/tarantool/blob/427fdaa77a2aaeecf685bdaa395b1fdfb26d4d82/src/box/errcode.h#L88) constant.

box.execute() was introduced instead of box.sql.execute() in 2.1 release series in the 2.1.1-478-gf66753ff4 commit (since 2.1.2 release) and in 2.2+ series since the 2.2.0-72-g9ebc41dc4 commit (since 2.2.1 release). Tarantool 1.10 has no SQL support at all (so neither box.execute(), nor box.sql.execute() are present in this release series).

Maybe different tarantool versions are in use?
